[tox]
envlist = py313
requires =
    keyrings.google-artifactregistry-auth

[testenv]
setenv =
    GOOGLE_APPLICATION_CREDENTIALS = {env:GOOGLE_APPLICATION_CREDENTIALS}
    PYTHONPATH = {toxinidir}

deps =
    --extra-index-url=https://us-central1-python.pkg.dev/x35-control-center/x35-pypi/simple
    -r requirements.txt
    -r requirements-tox.txt
commands =
    ruff check .
    ruff format . --check
    pytest --cov=src --cov-report=term-missing tests/unit

[coverage:run]
omit =
    */__init__.py

[pytest]
